rplidar_node:
  ros__parameters:
    channel_type: serial
    serial_port: /dev/radar
    serial_baudrate: 1000000
    frame_id: lidar_link
    topic_name: scan
    inverted: false
    angle_compensate: true
    scan_mode: Standard
    scan_frequency: 10.0
    enable_filter: true
    filter_inclusive: false
    filter_regions: [-92.0, -36.5, 80.0, 95.5, -139.0, -128.0, 133.0, 141.0]
